name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x] # NOTE: Keep in sync with README.
        # See Node.js release schedule: https://nodejs.org/en/about/previous-releases
        # - v22 EOL: Apr 30 2027
        # - v24 EOL: Apr 30 2028
        # - v26 EOL: Apr 30 2029
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: yarn install
      - run: yarn run prettier-check
      - run: yarn run eslint
